FROM apache/airflow:2.7.3-python3.8
USER root

# Install OpenJDK-11
RUN apt-get clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    apt-get install -y ant && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
ENV PATH $PATH:$JAVA_HOME/bin

USER airflow

COPY ./requirements.txt /
RUN pip install -r /requirements.txt

# COPY --chown=airflow:root ./dags /opt/airflow/dags