version: "3.3"
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8081:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port
    environment:
      - SPARK_MODE=master

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # Spark Worker UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077