file_name: Liquor_Sales
extension: .csv
tables: [
        {
            name: 'Items',
            columns: [
                {name: 'id', type: 'int'},
                {name: 'category_id', type: 'int'},
                {name: 'vendor_id', type: 'int'},
                {name: 'item_description', type: 'string'},
                {name: 'pack', type: 'int'},
                {name: 'bottle_volume_(ml)', type: 'number'},
                {name: 'state_bottle_cost', type: 'number'},
                {name: 'state_bottle_retail', type: 'number'}
            ]
        },
        {
            name: 'Category',
            columns: [
                {name: 'id', type: 'int'},
                {name: 'name', type: 'string'},
            ]
        },
        {
            name: 'Vendor',
            columns: [
                {name: 'id', type: 'int'},
                {name: 'name', type: 'string'},
            ]
        },
    ]
